### ISSUE TITLE
Proposal: @jfly as committer for asdf-direnv.

### ISSUE THREAD

**Issue by vic** [asdf-community/infrastructure#17]
Recently, @jfly has been contributing some good PR to asdf-direnv and seems to have been using it actively and finding things to improve. I believe - if that's right with you, @jfly - that having him and in general having more active users who are willing to send contributions as part of the team could help improving the project quality.

So I'm leaving this request to @jfly consideration, feel free to close this issue if you'd prefer not to. 

And if he agrees, could @smorimoto be so kind and add him, please ?
(Side question for @smorimoto, if I push or create a PR to this repo, the changes get automatically applied by some gh-action or is there something else to run ?)

**Comment by smorimoto** [comment]
@vic Sure! I can always take care of that. The current way to actually apply the code changes here is to use Terraform Cloud. I had invited you there in the past, but I just invited you again. Please check it when you have some time.

**Comment by smorimoto** [comment]
Note that if you are working with the GitHub Terraform provider, you should use direnv locally to expose the environment variable `GITHUB_TOKEN`. Basically, it still works, but when importing a repository, for example, it may not work as expected.

**Comment by jfly** [comment]
Thanks, @vic! I'd be happy to help out, although I'm not sure I fully understand what my responsibilities would be as a member of the team.

**Comment by vic** [comment]
Allowing contributions (issues/pull-reqs) to flow in the right direction. Being able to merge others and your own pull-requests, and generally: having a better eye than mine when reviewing pull-requests from a person who actually uses asdf-direnv :). It's all voluntary of course, as long and as far as you are willing.

**Comment by jfly** [comment]
Sounds good!
