### ISSUE TITLE
need some help with asdf-dasel

### ISSUE THREAD

**Issue by ghostsquad** [asdf-community/infrastructure#3]
it was initialized empty, and I don't have permissions to set the default branch or any other settings for branch protection etc.

**Comment by smorimoto** [comment]
The default branch has been changed. Perhaps we should change the repository permissions given to the maintainer.

**Comment by ghostsquad** [comment]
Yes please. I'd like a bit more control over some aspects.

**Comment by smorimoto** [comment]
I will do that.

**Comment by smorimoto** [comment]
https://github.com/asdf-community/infrastructure/commit/83cf430b64ba1c7c62eccb8938bae45a9c4d85cf
