### ISSUE TITLE
idea: template repo + new repos based on template repo

### ISSUE THREAD

**Issue by ghostsquad** [asdf-community/infrastructure#4]
if we create a template repo, new repos can be prepared with some good defaults and boilerplate

**Comment by smorimoto** [comment]
The template is already here: https://github.com/asdf-vm/asdf-plugin-template

**Comment by ghostsquad** [comment]
Ah, then we just need the terraform code to use the template when a new repo is created.

**Comment by smorimoto** [comment]
Yes, that’s correct.

**Comment by smorimoto** [comment]
and it can be done easily with this if necessary.
https://www.terraform.io/docs/providers/github/r/repository.html#template

**Comment by ghostsquad** [comment]
@smorimoto is there a PR that accomplishes this to cross-reference?

**Comment by ghostsquad** [comment]
if not, can we keep the issue open until a PR is merged?

**Comment by smorimoto** [comment]
It's not too difficult, but I'm busy this week and this isn't a rush task at all, so I can't work on this this week.

**Comment by smorimoto** [comment]
It may be done in the future, but there is no major problem at this moment, so I close this.
